spring:
  profiles:
    active: dev

server:
  port: 8080

# Pretty-print JSON responses
spring.jackson.serialization.indent_output: true

camel:
  springboot:
    # The Camel context name
    name: ${artifactId}
  # to reconfigure the camel servlet context-path mapping to use /api/* instead of /camel/*
  # needs to be in alignment with basePath in swagger definition
  component:
    servlet:
      mapping:
        context-path: /api/*
  # rest can also be configured here instead in the CamelRouter class
  # rest DSL configuration
  rest:
    component: servlet
    binding-mode: json
    enable-cors: true
  # jackson properties
  dataformat:
    json-jackson:
      object-mapper: jacksonObjectMapper

# all access to actuator endpoints without security
management:
  server:
    port: 8081
  security:
    enabled: false
  # expose actuator endpoint via HTTP
  endpoints:
    web:
      exposure:
#        include: info,health,camelroutes
        include: '*'
    # show verbose health details (/actuator/info) so you can see Camel information also
  endpoint:
    health:
      show-details: always
    # allow to obtain basic information about Camel routes (read only mode)
    camelroutes:
      enabled: true
      read-only: true

# Logging
logging:
  config: classpath:logback.xml
  level.org.springframework.web: DEBUG
---

spring:
  profiles: dev


---

spring:
  profiles: openshift
