== Swagger Contract First approach
== Spring Boot with generated Camel REST DSL API Configuration

The project generates resources based on the swagger.json specification stored in resources folder
and new resources are packeged in swager.api and swagger.model

=== Camel routes

The Camel route is located in the `MyCamelRouter` class. In this class the route
starts from a timer, that triggers every 2nd second and calls a Spring Bean `MyBean`
which returns a message, that is routed to a stream endpoint which writes to standard output.

=== Using Camel components

Apache Camel provides 200+ components which you can use to integrate and route messages between many systems
and data formats. To use any of these Camel components, add the component as a dependency to your project.

=== How to run

You can run this example using

    mvn spring-boot:run

=== To get info about the routes

To show a summary of all the routes

----
curl -XGET -s http://localhost:8080/camelroutes
----

To show detailed information for a specific route

----
curl -XGET -s http://localhost:8080/camelroutes/{id}/detail
----


=== More information

You can find more information about Apache Camel at the website: http://camel.apache.org/



