== Swagger Contract First approach
== Spring Boot with generated Camel REST DSL API Configuration

The project generates resources based on the swagger.json specification stored in resources folder
and new resources are packeged in swager.api and swagger.model

=== How to generate artifacts

After placing your api definition (swagger.json) file into 'resources' folder
You can run following comand to generate the artifacts

    mvn clean compile

=== How to run

You can run this example using

    mvn spring-boot:run

=== To get info about application health

----
curl -XGET -s http://localhost:8081/actuator/health
----

=== To get info about the routes

To show a summary of all the routes

----
curl -XGET -s http://localhost:8081/actuator/camelroutes
----

To show detailed information for a specific route

----
curl -XGET -s http://localhost:8081/actuator/camelroutes/{id}/detail
----

=== More information

You can find more information about Apache Camel at the website: http://camel.apache.org/



