spring:
  profiles:
    active: dev

server:
  port: 8080

camel:
  springboot:
    # The Camel context name
    name: camelREST
    main-run-controller: true
    health.indicator.enabled: true
  # to reconfigure the camel servlet context-path mapping to use /api/* instead of /camel/*
  component:
    servlet.mapping.context-path: /api/*
  # rest can also be configured here instead in the CamelRouter class
  # rest DSL configuration
  rest:
    component: servlet
    binding-mode: json
    enable-cors: true
    port: 8080
    context-path: /api
  # rest DSL api-doc configuration
    api-context-path: /api-doc

# what to say
greeting: Hello World

# how often to trigger the timer
timer.period: 2000

management:
  security:
    enabled: false
  # expose actuator endpoint via HTTP
  endpoints:
    web.exposure.include: info,health,camelroutes
    # show verbose health details (/actuator/info) so you can see Camel information also
    health.show-details: always
    # allow to obtain basic information about Camel routes (read only mode)
    camelroutes:
      enabled: true
      read-only: true
    # to turn off Camel info in (/actuator/info)
    #info.camel.enabled=false

# Logging
logging:
  config: classpath:logback.xml
  level:
    org.springframework: INFO
    apache.camel.spring.boot: INFO
    org.apache.camel.impl: DEBUG

---

spring:
  profiles: dev


---

spring:
  profiles: openshift
